### ISSUE TITLE
 infer_yolo_v7 / infer_deepsort algorithm is installed but not functional

### ISSUE THREAD

**Issue by LyCrash** [Ikomia-dev/IkomiaApi#29]
I've got the same problem as @tonnys due to infer_yolo_v7 and bypassed the error as @LudoBar mentioned, then as I am using deepsort algorithm too so I tried to solve the same problem of: 

> Algorithm infer_deepsort is installed locally but not functional.

 by manually install all requirements file, so I run:
`pip install -r C:\Users\HP-PC\Ikomia\Plugins\Python\infer_deepsort\requirements1.txt`

and it works fine, but with the 2nd file (**requirements2.txt**), I get this error:

Collecting git+https://github.com/KaiyangZhou/deep-person-reid.git@6987d99074fcc63146660b83b38218c37b4412b3 (from -r C:\Users\HP-PC\Ikomia\Plugins\Python\infer_deepsort\requirements2.txt (line 2))
  Cloning https://github.com/KaiyangZhou/deep-person-reid.git (to revision 6987d99074fcc63146660b83b38218c37b4412b3) to c:\users\hp-pc\appdata\local\temp\pip-req-build-dqemcbzw
  Running command git clone --filter=blob:none --quiet https://github.com/KaiyangZhou/deep-person-reid.git 'C:\Users\HP-PC\AppData\Local\Temp\pip-req-build-dqemcbzw'
  Running command git rev-parse -q --verify 'sha^6987d99074fcc63146660b83b38218c37b4412b3'
  Running command git fetch -q https://github.com/KaiyangZhou/deep-person-reid.git 6987d99074fcc63146660b83b38218c37b4412b3
  Running command git checkout -q 6987d99074fcc63146660b83b38218c37b4412b3
  Resolved https://github.com/KaiyangZhou/deep-person-reid.git to commit 6987d99074fcc63146660b83b38218c37b4412b3
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "D:\2CS_esi\S1\SCI\iot_project\Project\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\2CS_esi\S1\SCI\iot_project\Project\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\2CS_esi\S1\SCI\iot_project\Project\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\HP-PC\AppData\Local\Temp\pip-build-env-ea5z1c88\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\HP-PC\AppData\Local\Temp\pip-build-env-ea5z1c88\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\HP-PC\AppData\Local\Temp\pip-build-env-ea5z1c88\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\HP-PC\AppData\Local\Temp\pip-build-env-ea5z1c88\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

_Originally posted by @LyCrash in https://github.com/Ikomia-dev/IkomiaApi/issues/1#issuecomment-1961413306_

**Comment by LudoBar** [comment]
Hi @LyCrash,

The error indicates that numpy is missing from your Python environment. It's quite strange as Numpy is a direct dependency of Ikomia package. Could you check the numpy installation (with `pip list` for example)?
